from datetime import datetime
from uuid import uuid4
from zoneinfo import ZoneInfo

from sqlalchemy import UUID, DateTime, Float, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class AISMessageDB(Base):
    """
    Table storing raw AIS messages received by the API.
    These messages are later used to build sliding windows
    for feature engineering and prediction.
    """

    __tablename__ = "ais_messages"

    __table_args__ = (Index("idx_mmsi_timestamp", "mmsi", "timestamp"),)

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    mmsi: Mapped[int] = mapped_column(
        Integer,
        index=True,
        nullable=False,
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        index=True,
        nullable=False,
    )

    lat: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    lon: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    sog: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    cog: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    heading: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    rot: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    draught: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    special_manoeuvre_indicator: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now(ZoneInfo("UTC")),
        nullable=False,
    )


class PredictionDB(Base):
    """
    Table storing predictions generated by the model.
    This enables offline evaluation once ground truth
    labels are later provided.
    """

    __tablename__ = "predictions"

    id: Mapped[str] = mapped_column(
        UUID,
        primary_key=True,
        default=uuid4(),
    )

    mmsi: Mapped[int] = mapped_column(
        Integer,
        index=True,
        nullable=False,
    )

    timestamp: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
    )

    predicted_label: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )

    predicted_class: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    prob_moving: Mapped[float] = mapped_column(Float, nullable=False)

    prob_docked: Mapped[float] = mapped_column(Float, nullable=False)

    prob_drifting: Mapped[float] = mapped_column(Float, nullable=False)

    prob_anchored: Mapped[float] = mapped_column(Float, nullable=False)

    model_name: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )

    model_version: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )

    model_type: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now(ZoneInfo("UTC")),
        nullable=False,
    )


class GroundTruthDB(Base):
    """
    Stores ground truth labels submitted by the client.
    Used later to evaluate model performance.
    """

    __tablename__ = "ground_truth"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    prediction_id: Mapped[str] = mapped_column(
        String,
        index=True,
        nullable=False,
    )

    true_label: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )

    true_class: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now(ZoneInfo("UTC")),
        nullable=False,
    )
